#include <QApplication>
#include <QMainWindow>
#include <QDebug>
#include <QSignalMapper>
#include <QWidget>
#include <QLabel>
#include <QSettings>
#include <QPushButton>
#include <QToolButton>
#include <QString>
#include <QLineEdit>
#include <QPixmap>
#include <QFileDialog>
#include <QScrollBar>
#include <QGraphicsView>
#include <QTimer>

#include <QStyleFactory>
#include <QWindow>
#include <QKeyEvent>
#include <QOpenGLContext>
#include <QOpenGLPaintDevice>
#include <QOpenGLFunctions>
#include <QPainter>
